import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Conduit',
  description: 'Terms and conditions for using the Conduit AI-native content operations platform.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-lg font-bold tracking-tight">Conduit</Link>
          <Link href="/" className="text-sm text-muted-foreground hover:text-foreground transition-colors">&larr; Back to home</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-black mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-12">Last updated: March 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Conduit (&ldquo;the Platform&rdquo;), operated by DigitalHustle, you agree to be bound by these Terms of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the Platform. We may update these Terms at any time; continued use after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">2. Account Registration</h2>
            <p className="text-muted-foreground leading-relaxed">
              To use Conduit, you must create an account using a valid email address or Google OAuth. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must be at least 16 years old to use the Platform. You agree to provide accurate and complete information and to update it as needed.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">3. Your Content &amp; Ownership</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              <strong className="text-foreground">You own all content you create with Conduit.</strong> This includes articles, keywords, media, collections, and any other materials you produce using the Platform, including content generated by AI agents on your behalf.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-3">
              <strong className="text-foreground">AI-generated content:</strong> Content produced by AI agents (Content Autopilot, Content Refresh, etc.) is your property. You retain full rights to use, publish, modify, and commercialize AI-generated content without restriction.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              You grant Conduit a limited, non-exclusive license to store, process, and display your content solely for the purpose of providing the Platform&apos;s services to you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">4. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">You agree not to:</p>
            <ul className="list-disc list-inside text-muted-foreground space-y-2 leading-relaxed">
              <li>Use the Platform to generate illegal, harmful, or deceptive content</li>
              <li>Attempt to circumvent AI credit limits or abuse the AI proxy</li>
              <li>Reverse-engineer, decompile, or disassemble any part of the Platform</li>
              <li>Use automated scripts to access the Platform (except via our published APIs)</li>
              <li>Impersonate another person or entity</li>
              <li>Interfere with the Platform&apos;s security or infrastructure</li>
              <li>Resell access to the Platform without a white-label agreement</li>
              <li>Generate content that violates third-party intellectual property rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">5. Subscription Plans &amp; Payments</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              Conduit offers Free, Pro ($29/month), Business ($99/month), and BYOK (free) plans. Paid subscriptions are billed monthly through Stripe. Prices are in USD and exclude applicable taxes.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-3">
              <strong className="text-foreground">AI Credits:</strong> Each plan includes a set number of AI calls per month. Unused credits do not roll over. If you exceed your plan&apos;s limit, AI features will be paused until your next billing cycle.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              <strong className="text-foreground">BYOK Plan:</strong> The Bring Your Own Key plan allows unlimited AI calls using your own API keys from supported providers. You are responsible for any costs incurred with those providers.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">6. Cancellation &amp; Refunds</h2>
            <p className="text-muted-foreground leading-relaxed mb-3">
              You may cancel your subscription at any time from your account settings. Cancellation takes effect at the end of your current billing period. You retain access to paid features until then.
            </p>
            <p className="text-muted-foreground leading-relaxed">
              Refunds are handled on a case-by-case basis. If you are unsatisfied within the first 14 days of a paid subscription, contact us for a full refund. After 14 days, no refunds are provided for partial billing periods.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">7. AI Services Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              Conduit uses third-party AI providers (Anthropic, OpenAI, Google, Mistral, Groq) to generate content. AI-generated content may contain inaccuracies, biases, or errors. You are responsible for reviewing and editing all AI-generated content before publishing. Conduit does not guarantee the accuracy, quality, or originality of AI outputs.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">8. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, Conduit and DigitalHustle shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the Platform. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">9. Service Availability</h2>
            <p className="text-muted-foreground leading-relaxed">
              We strive for high availability but do not guarantee uninterrupted access. The Platform may be temporarily unavailable for maintenance, updates, or circumstances beyond our control. We will provide reasonable notice of planned maintenance when possible.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">10. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">
              We may suspend or terminate your account if you violate these Terms or engage in activity that harms the Platform or other users. Upon termination, you may export your data within 30 days. After that period, your data will be permanently deleted.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">11. Dispute Resolution</h2>
            <p className="text-muted-foreground leading-relaxed">
              Any disputes arising from these Terms or your use of Conduit shall first be resolved through good-faith negotiation. If negotiation fails, disputes shall be resolved through binding arbitration in accordance with applicable rules, rather than in court. You agree to waive any right to participate in a class action lawsuit.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">12. Governing Law</h2>
            <p className="text-muted-foreground leading-relaxed">
              These Terms are governed by and construed in accordance with applicable law, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">13. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              Questions about these Terms? Contact us at legal@getconduit.io or visit our <Link href="/contact" className="text-primary hover:underline">Contact page</Link>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-border py-8 px-6">
        <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-muted-foreground">&copy; 2026 Conduit by DigitalHustle</p>
          <div className="flex gap-6 text-xs text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/security" className="hover:text-foreground transition-colors">Security</Link>
            <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
